export default {
    ACCESS_TOKEN_PRIVATE_KEY: "ACCESS_TOKEN_PRIVATE_KEY",
    ACCESS_TOKEN_PUBLIC_KEY: "ACCESS_TOKEN_PUBLIC_KEY",
    REFRESH_PRIVATE_KEY: "REFRESH_PRIVATE_KEY",
    REFRESH_PUBLIC_KEY: "REFRESH_PUBLIC_KEY",
    DB_CONNECTION: "DB_CONNECTION",
    SERVER_PORT: "SERVER_PORT",
    SERVER_HOST: "SERVER_HOST",
    ACCESS_TOKEN_TTL: 'ACCESS_TOKEN_TTL',
    REFRESH_TOKEN_TTL: 'REFRESH_TOKEN_TTL',
    SALT_ROUND_FACTOR: 'SALT_ROUND_FACTOR',
  };